// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Types will be generated after migration

const SUPABASE_URL = "https://kkgddsiddegqxinuepcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZ2Rkc2lkZGVncXhpbnVlcGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzYxMzcsImV4cCI6MjA2OTAxMjEzN30.Q6lPxNp61-zVVdHI2BX70ltDhDofixWqMYimJ6WBAK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});